### PR TITLE
Feature/navigation bar :DO NOT MERGE

### LINKED ISSUE #23: Tests are broken
Seems that some files are missing for the test script to work correctly:

```shell
[william@william-pc coding-coach]$ yarn test
yarn run v1.9.4
$ node scripts/custom-config test --env=jsdom
/home/william/Dev/Self/WNemencha/coding-coach/node_modules/proxyquire/lib/proxyquire.js:161
    throw err
    ^

Error: Cannot find module '../utils/createJestConfig' from '/home/william/Dev/Self/WNemencha/coding-coach/node_modules/react-scripts/scripts'
    at Function.module.exports [as sync] (/home/william/Dev/Self/WNemencha/coding-coach/node_modules/resolve/lib/sync.js:43:15)
    at Proxyquire._resolveModule (/home/william/Dev/Self/WNemencha/coding-coach/node_modules/proxyquire/lib/proxyquire.js:137:20)
    at Proxyquire.<anonymous> (/home/william/Dev/Self/WNemencha/coding-coach/node_modules/proxyquire/lib/proxyquire.js:205:35)
    at Array.reduce (<anonymous>)
    at Proxyquire._withoutCache (/home/william/Dev/Self/WNemencha/coding-coach/node_modules/proxyquire/lib/proxyquire.js:204:6)
    at Proxyquire.load (/home/william/Dev/Self/WNemencha/coding-coach/node_modules/proxyquire/lib/proxyquire.js:129:15)
    at Object.<anonymous> (/home/william/Dev/Self/WNemencha/coding-coach/scripts/custom-config.js:39:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### LINKED ISSUE #34: Account Settings
**Acceptance Criteria:**

A user can update the following required fields:
- Name
- Email address
- Job title
- Languages the user speaks

A user can update the following optional fields:
- Social media accounts
- Company
- Skills to mentor in (depends on account type)
- Skills to be mentored in depends on account type)

Users will be able to set their account type to be mentor, mentee, or both.

A mentor can update the following fields:
- Skills they are able to mentor in
- Proficiency of skills they are able to mentor in

A mentee can update the following fields:
- Skills they are looking to improve

All users are able to set themselves as a mentor.

### LINKED ISSUE #42: Delete Account
**Acceptance Criteria:**
- Users can delete their accounts.
- This will remove all data from the database.
- All current mentorships will be notified.

### PR DESCRIPTION
**Pull request by nitish24p**
# Details

## Steps to QA

- [ ] Step 1

## Issue

Closes #123

This closes #34, closes #23, and closes #42

### CODE REVIEW

**Comment by tureey** [comment]
@nitish24p We have labels to indicate the state of a branch. I'll assigned the: `In progress`

**Comment by emmawedekind** [comment]
This PR isn't ready for review yet, right?

**Comment by nitish24p** [comment]
@emmawedekind no i've not pushed my final changes yet. Waiting for the icons but i'll push it with dummy text for the time being :)

**Comment by emmawedekind** [comment]
Okay great, the icons will take a couple more days, then we can continue, thanks!

**Comment by crysfel** [comment]
Closing due to inactivity

**Pull request closed without merging**
