### PR TITLE
First approach Report Abuse

### LINKED ISSUE #157: Report Abuse task flow
Create a UX flow diagram for reporting abuse from the Dashboard View (see `design` branch for instruction and the full information architecture diagram).

### PR DESCRIPTION
**Pull request by tureey**
# Details

This is a first approach for the Report Abuse Task Flow.
This PR will can be used to talk about some standards we can decide.

## Description

Create a Task flow for the Report Abuse

## Issue

closes #157

### CODE REVIEW

**Comment by tureey** [comment]
this is a my Task flow ever so please:
- Make me know all the mistakes I did
- Recommend me readings if needed

Would be crazy to declare some colors as standards for a few things? _For Example, All the views should be as rectangle yellow, all the flow that represent the "no" of an Evaluation, in red etc..._

@Venablena I propose this to have standards for everyone

**Comment by tureey** [comment]
@Venablena @emmawedekind is she not active anymore?

**Comment by crysfel** [comment]
@tureey I haven't seen her in a while, maybe because of the holidays

**Comment by tureey** [comment]
What holidays? 🤔 @crysfel

**Comment by emmawedekind** [comment]
Looks good. I'll merge.

**Pull request merged**
