### PR TITLE
Sign up/sign in with social media

### LINKED ISSUE #222: Sign Up With Social Media (O-Auth) - Mobile
image

### PR DESCRIPTION
**Pull request by linux-nerd**
# Details

## Description
- [x] Add `onClick` to Icon component
- [x] Add FacebookLogin Component to handle the login from fb
- [x] Add withLogin HOC to handle the app flow after the token is returned from oAuth provider. Since the service is not yet ready, it does not do anything fancy and logs the data to the console.
- [ ] Add TwitterLogin component
- [ ] Add GithubLogin component
- [x] Add InstagramLogin component

## Issue

closes #222

### CODE REVIEW

**Comment by emmawedekind** [comment]
How's this going?

**Comment by linux-nerd** [comment]
> How's this going?

Hey @emmawedekind, I will resume the work from tomorrow.

**Comment by emmawedekind** [comment]
Great thanks!

**Comment by crysfel** [comment]
We decide to use Auth0 to handle autentication

**Pull request closed without merging**
