### PR TITLE
Remove unused NPM dependencies and add missing peer dependencies

### PR DESCRIPTION
**Pull request by trent-boyd**
# Details

Terminal output after a typical `yarn install`:

``` sh
[3/4] 🔗  Linking dependencies...
warning " > babel-loader@8.0.4" has unmet peer dependency "webpack@>=2".
warning " > file-loader@2.0.0" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning " > sass-loader@7.1.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
warning " > @lingui/cli@2.7.2" has unmet peer dependency "babel-plugin-macros@^2.4.2".
warning "@storybook/addon-viewport > @emotion/styled > @emotion/styled-base@0.10.6" has unmet peer dependency "@emotion/core@0.x.x".
warning " > css-loader@1.0.1" has unmet peer dependency "webpack@^4.0.0".
warning " > eslint-config-prettier@3.3.0" has unmet peer dependency "eslint@>=3.14.1".
warning " > eslint-plugin-babel@5.3.0" has unmet peer dependency "eslint@>=4.0.0".
warning " > eslint-plugin-prettier@3.0.0" has unmet peer dependency "eslint@>= 5.0.0".
```

## Description

Original discussion [here on Slack](https://coding-coach.slack.com/archives/CCQDTKZC2/p1545952765021900).

The app currently has a few Webpack loaders listed as dependencies that are not being used anymore. We are also directly referencing `eslint` as part of our precommit Husky hook, but it's currently hoisted from `react-scripts`. It's best practice to add it as a direct dependency, just in case we have tor remove `react-scripts` for whatever reason. :)

There are also a couple of complaints from `yarn` about missing peer dependencies. I've added them, but from what I can tell there's nothing actually breaking. These are:

1. `@emotion/core`, listed as a peer dependency of Storybook's Viewport plugin.
2. `babel-plugin-macros`, listed as a peer dependency of LinguiJS and Storybook.
3. `webpack`, listed as a peer dependency of `babel-loader`.

## Steps to QA

- [ ] Run `yarn install`.
- [ ] Verify that there are no more warnings as seen above.
- [ ] Verify that the `yarn start` and `yarn run storybook` commands behave as intended.
- [ ] Verify that the `yarn run test` command has no Babel- or Webpack-related errors.

### CODE REVIEW

**Comment by emmawedekind** [comment]
This is what I got after running `yarn` and trying `yarn start`. Am I missing something?

image

**Comment by trent-boyd** [comment]
@emmawedekind: I'm familiar with that error from CRA, but I wasn't running into it when I pushed last. I'll double check when I get off work, and either fix the issue or provide you with better details.

**Comment by trent-boyd** [comment]
My bad @emmawedekind. I forgot to push some `yarn.lock` updates. `yarn install` should be pulling in the right version of `babel-loader` now, so you won't get that error anymore. 🤞

**Comment by trent-boyd** [comment]
I see Travis is still complaining about the same issue. I'll double-double check.

**Comment by trent-boyd** [comment]
Found the issue. In `"babel-loader": "^8.0.4"`, version `8.0.5` is acceptable. So I removed the caret to lock down to `8.0.4`, which is what `react-scripts` expects. 🎉

**Comment by crysfel** [comment]
I'm still getting a couple warning, is this expected?

screen shot 2019-01-09 at 12 00 03 pm

**Comment by trent-boyd** [comment]
@crysfel: I'm stumped! I've pulled in the dev branch, and I'm not getting that locally at all. I noticed that Travis is also getting the warnings, but that it's using a cache.

Here's what I get after I run `rm -rf node_modules && yarn cache clean`.

image

**Comment by trent-boyd** [comment]
Ah, I see. I downgraded to `1.3.2` and I'm seeing the same thing now. I'll push something up tonight. 👍 

Thanks for looking!

**Comment by trent-boyd** [comment]
Hmm, it seems like this has been an [ongoing issue](https://github.com/yarnpkg/yarn/issues/4850) with Yarn since `1.2.1`. Perhaps it's a fool's errand to attempt to clean up every single warning. I _have_ run into legitimate issues when a peer dep isn't installed, but that doesn't seem to be the case here.

I'm debating closing this for simplicity's sake. @crysfel, do you have a strong opinion either way on this?

**Pull request merged**
