### PR TITLE
Add translation static image landing page

### PR DESCRIPTION
**Pull request by tureey**
# Details

## Description
Add translations for static images.

## Issue
https://github.com/Coding-Coach/coding-coach/issues/75

### CODE REVIEW

**Comment by emmawedekind** [comment]
This image is going away - do we really need to fix it?

**Comment by tureey** [comment]
I don't think so. But I did it because it took me 10 seconds

**Comment by tureey** [comment]
If #71 fixed this, lets close this one then

**Comment by crysfel** [comment]
This code doesn't exist anymore

**Pull request closed without merging**
