### PR TITLE
Refactor/contact

### PR DESCRIPTION
**Pull request by Venablena**
# Details
Contact is the only section on the homepage with its own component, the others use the HomeSection template.

## Description
Refactors Contact section to use HomeSection to improve consistency and readability. 

##Issue
I created an issue for this but because I couldn't assign it to myself and I already did the refactoring, I closed it and just went ahead with this pull request.

### CODE REVIEW

**Comment by crysfel** [comment]
Some tests are failing, can you please take a look?

**Comment by Venablena** [comment]
Thanks! I removed the unnecessary files and made the requests as per @tureey 's request.
Adding a snapshot test to HomeSection doesn't seem very useful, though, how would you test the props that are passed in there? The test doesn't fail but it warns about the props: 
` Warning: Failed prop type: The prop `media` is marked as required in `HomeSection`, but its value is `undefined`.`

**Comment by tureey** [comment]
1. I would test that the `Home`. I said to test HomeSection because we had a Contact component but, since it's only for encapsulation in a `page`, I would only test the `Home Page`.
2. Can you provide an image about the undefined? That's weird!
3. Since I forgot to add the `Proptype` definition for the `prop id` could you add it please?

@Venablena

**Comment by Venablena** [comment]
@tureey 
1. The Home page already has a test although it's pretty basic. 
2. I'm not on my computer right now but what happens is that a snapshot test only creates a very basic component with the header and divs and no content from children or props. So I'm really wondering about the technique here -how do you test props without mocking them (in a lot of docs Kent C Dodds is adamantly against mocking) -and is it useful? He's not a huge fan of snapshot testing either, nor am I...

**Comment by tureey** [comment]
I still have pending to watch and read his posts about it! I'll do it this weekend if I can.
I don't know the solution... I never did UI testing.

Does anyone have knowledge on this subject? @crysfel @emmawedekind @arthurbuhl I don't know who else tag!

**Comment by crysfel** [comment]
I'm not a fun of snapshot testing, this is the first time I'm working in a project with such tests.

**Comment by tureey** [comment]
I am not even a fan of UI Testing hahaha 👎 (I know people will kill me)

**Comment by Venablena** [comment]
@tureey I must admit I'm in your camp. So I just removed the whole extra test because it doesn't seem to be adding anything useful and it's very easy to add back if we want later. And added that missing `propType`. Hope all is good now. @emmawedekind , @crysfel Once that panel component is good to go, ping me if you want me to add it to this and the footer.

**Comment by Venablena** [comment]
@crysfel  I really want to understand the whole testing approach better, how would you use this library to test individual components without snapshots? Or would you test individual components at all?

**Comment by Venablena** [comment]
@tureey Did you want to tweak something else about this or are we good to go?

**Comment by emmawedekind** [comment]
Please fix the merge conflicts :)

**Comment by Venablena** [comment]
Conflicts fixed but looks like it's asking for reviews again.

**Comment by tureey** [comment]
Good job! And sorry for fixing clonflicts more than once...

**Comment by emmawedekind** [comment]
This is so wonderful thanks so much!

**Pull request merged**
