### PR TITLE
Fix: remove airbnb linter and fix image import

### PR DESCRIPTION
**Pull request by DennisKo**
Development was erroring out with some lint error. 

```
Configuration for rule "react/jsx-no-bind" is invalid:
Value "[object Object]" should NOT have additional properties.
```

See: https://github.com/airbnb/javascript/issues/1893

This was because of a version mismatch of eslint (react-scripts depends on some old version I guess..). It was not fixable in a "clean" way...
So for now just remove airbnb linting until we figure out the rest of the archtitecture...

### CODE REVIEW

**Comment by palashmon** [comment]
Looks like a duplicate of #12 

```js
import mentorImage from "./images/mentor.jpg";
```

**Comment by DennisKo** [comment]
You are right! Eslint wouldnt allow requiring inline like this. Thats why this had to be in here...

**Comment by emmawedekind** [comment]
So do we need this one as well as #12?

**Comment by DennisKo** [comment]
2 Options to get a working development:

- Merge https://github.com/Coding-Coach/coding-coach/pull/12 and update&merge this
- merge this directly, discard https://github.com/Coding-Coach/coding-coach/pull/12

**Comment by reeversedev** [comment]
Looks like #12 going to get wasted for sure.

**Comment by reeversedev** [comment]
Looks like #12 going to get wasted for sure. Lol.

**Pull request merged**
