### PR TITLE
Pagination for blog

### PR DESCRIPTION
**Pull request by alizand1992**
Some notes:
* This is based on master and not develop since blog exist in master.
* I wanted to know if the way I solved this is acceptable before I refactor. please let me know if this is ok so I can start refactoring
* How many posts per page should this show?
* should the page numbers show if there is only one page?
* if the number of pages is more than the width of the screen, this will create a new row. if this is not acceptable, please provide a design for what it should look like if there are many pages.

### CODE REVIEW

**Comment by alizand1992** [comment]
@crysfel Would you be able to look at my commit and notes please? I'm eager to fix any issues that it may have.

**Comment by crysfel** [comment]
I'm so sorry for the late response 😅

answering your questions:

> * This is based on master and not develop since blog exist in master.
Yes, we should delete develop. Will do that soon

> * How many posts per page should this show?
Maybe 10 would be a good number

> * should the page numbers show if there is only one page?
No, just hide the component

> * if the number of pages is more than the width of the screen, this will create a new row. if this is not acceptable, please provide a design for what it should look like if there are many pages.
For now is fine... we can deal with that when the time comes 😬

**Comment by alizand1992** [comment]
@crysfel Awesome. I will make the changes

**Comment by crysfel** [comment]
@alizand1992 ping me on slack if something is not clear or if you need help

**Comment by OmarMoataz** [comment]
hey @crysfel, is this feature still under development? Can I pick up Alizand left off?

**Comment by crysfel** [comment]
@OmarMoataz  That would be awesome!

**Comment by OmarMoataz** [comment]
I can start working on this the week after next just so you know. :)

**Pull request closed without merging**
