### PR TITLE
Reword action for user to take.

### PR DESCRIPTION
**Pull request by enriquezm**
# Details

## Description

Changed the wording from "join" to "sign in". It's small change, but seeing that I was confused as to whether the link was to request an invite link or signing into the actual slack channel, the wording could help out future contributors/etc.

### CODE REVIEW

**Comment by emmawedekind** [comment]
But this isn't about the user signing into Slack, it's about them joining the organization.

**Comment by tureey** [comment]
I think as @emmawedekind

**Comment by crysfel** [comment]
Closing this PR, we want user to join the organization 😁

**Comment by emmawedekind** [comment]
No problem!

**Pull request closed without merging**
