### PR TITLE
WIP: Feature/automate deployment

### PR DESCRIPTION
**Pull request by linux-nerd**
# Details

## Description

- [x] Create 4 stages - Lint, Test, Build and Deploy
- [x] Skip Deploy stage for non master branch
- [x] Add SSH key to travis ci as env variable
- [x] Add email and name as travis ci env variable
- [ ] Run Deploy Stage for master branch

## Blocker
Not able to access env variables from travis script 😞 

## Screenshots

1. For branch other than master
screen shot 2018-11-06 at 10 06 37 pm

2. For master branch
screen shot 2018-11-06 at 10 09 43 pm

3. Travis CI env variable
screen shot 2018-11-06 at 10 14 50 pm

4. Not able to access travis ci env variables
screen shot 2018-11-06 at 10 17 13 pm

## Issue
#214

### CODE REVIEW

**Comment by crysfel** [comment]
@linux-nerd I had the same issue when working with the Donate button, I defined the ID inside a variable but Travis didn't read the value, the weirdest thing is that a couple days later some tests failed because travis started reading the value O.o

Probably is an issue with Travis, if we can't find a solution to this we should consider using a different CI

**Comment by linux-nerd** [comment]
@crysfel I noticed that the variables are not accessible from within the git commands, otherwise the variables are accessible.

screen shot 2018-11-08 at 12 02 55 pm

**Comment by linux-nerd** [comment]
I have opened a question on [stackoverflow](https://stackoverflow.com/questions/53202626/travis-ci-variables-not-accessible-from-travis-ci-yml)

**Comment by emmawedekind** [comment]
Hey @linux-nerd what's happening here :)

**Comment by linux-nerd** [comment]
> Hey @linux-nerd what's happening here :)

Not able to proceed due to lack of info. No response on the SO question and couldn't find any documentation.  😞

**Comment by crysfel** [comment]
I'm closing this as work is not completed

**Pull request closed without merging**
