### PR TITLE
Simpler solution for Panel components tailwind css

### PR DESCRIPTION
**Pull request by dlofran2**
# Details

## Description
Removes the calcheight plugin, instead uses flexbox to create the Panel component.   

## Steps to QA
Load my PR code and https://codingcoach.io/ at the same time and compare the Panel component UI.
**Important Note** You will notice some changes like button is not aligned, and the 'Last updated' will be different sizes. 
* The button is different because it has not been converted to tailwind yet so the new css is overwriting it.  (I did a minor test to make sure that this was what was happening, switching some of the button css did resolve the issue but thats not what this PR is for)
* The 'Last updated' change when it was changed to markup.  Now, instead of a `small` tag, it is being represented as an `h4` (not sure if this is meets accessibility standards because it skips from `h2` to `h4`), but we will need to discuss how that should be resolved separately. 

**Side note**
* Changed both `h1` in the markdown to `h2` as they were before. 

## Screenshots
screen shot 2018-12-07 at 7 47 16 pm
screen shot 2018-12-07 at 7 47 03 pm
screen shot 2018-12-07 at 7 46 47 pm

### CODE REVIEW

**Comment by emmawedekind** [comment]
Looks great thanks!

**Comment by emmawedekind** [comment]
Please fix the `tailwind.js` conflict and we'll merge it in!

**Comment by jwithington** [comment]
@dlofran2 : are you still working on this? if you/the project needs someone to work on those merge conflicts, I'm interested. 😀

**Comment by tureey** [comment]
It was finished. He only had to solve the conflicts! @jwithington

**Comment by crysfel** [comment]
@jwithington please go ahead!

**Comment by palashmon** [comment]
Hi @jwithington, could you please provide an update on this? Thanks!

**Comment by tureey** [comment]
ping @jwithington

**Comment by jwithington** [comment]
Oh hey! I clearly missed these notifications -- I can take a look!

**Comment by jwithington** [comment]
Hey all --

unless I'm doing this wrong, I'm not seeing any merge conflicts. Steps I took:

- checkout `git checkout -b pull/origin/252`
- merge it into local `develop`

...no conflicts resulted. 

I'm pretty new to merging forks from other folks, so do let me know if I missed something. Thanks!

**Comment by tureey** [comment]
@jwithington Here in the PR appears that there are conflicts though :thinking: 

Try of pulling the remote maybe? @crysfel any idea?

**Comment by crysfel** [comment]
🤔 it looks to me that the remotes might be wrong? What do you get if you run `git remove -v`?

**Comment by crysfel** [comment]
Thanks for contributing. We are migrating the landing page to gatsby, therefore this codebase is deprecated.

**Pull request closed without merging**
