### PR TITLE
Created mentorship-guidelines md

### LINKED ISSUE #391: Turn Mentorship Guidelines into web page
Currently, the "mentorship guidelines" is a [Google Doc](https://docs.google.com/document/d/1zKCxmIh0Sd4aWLiQncICOGm6uf38S0kJ0xb0qErNFVA/edit).

The task is to turn it into a webpage (similar to https://codingcoach.io/legal/cookies [[source code](https://github.com/Coding-Coach/coding-coach/blob/master/content/legal/cookies.md)]) for better SEO and performance.

### PR DESCRIPTION
**Pull request by TommiKorhonen**
Turned Mentorship Guidelines into a web page.
Resolve #391 :)

### CODE REVIEW

**Comment by moshfeu** [comment]
Thank you!
Here are some comments.

1. Let's add `h1` "Mentorship Guidelines" [reference from cookies](https://user-images.githubusercontent.com/3723951/127113684-b186c868-6c19-4a4f-a5d5-e4d70a24de86.png)
2. Let's remove the current title and image (because we know in the context of the website) [here](https://user-images.githubusercontent.com/3723951/127113841-0babe3a9-5011-4ce2-8316-4075cd85c195.png)
3. Let's reduce the illustration images to `max-width: 50%` similar to how they presented in the Google doc (like [this](https://user-images.githubusercontent.com/3723951/127114672-d39dafe4-a7bd-4f99-b655-749c2fdc319c.png))

**Comment by moshfeu** [comment]
4. I'd also move it from legal to new folder, let's say _guidelines_. I believe it requires to add this folder to the [config file](https://github.com/Coding-Coach/coding-coach/blob/93b4612fbe3ad697cd2a0586fe9d3e0a727ece5b/gatsby-config.js#L31-L37), just like _legal_. Can you try that?

**Comment by TommiKorhonen** [comment]
Sure, I look into it!

**Comment by TommiKorhonen** [comment]
Added all things @moshfeu asked. Also added maxWidth: 1/2=50% to tailwind config.

**Comment by moshfeu** [comment]
Sorry for the late response. I deleted some folders which apparently was important for running this project.
Anyway, apparently, it wasn't enough just to add _guidelines_ to the config so I've made some fixes.
Please let me last approval before I merge.
Thanks!

**Comment by TommiKorhonen** [comment]
Np, approved. Ty!

**Review by moshfeu — APPROVED** [review]
Thank you!

**Pull request merged**
