### PR TITLE
Updating test email to coding coach email

### PR DESCRIPTION
**Pull request by emmawedekind**
This PR removes the test@example.com env that was being shown in the UI and replaces it with the Gmail account.

### CODE REVIEW

**Comment by AustinPaquette** [comment]
Was just going to come here and make a PR if one wasn't already made 🤣

**Comment by frederikprijck** [comment]
Might be interesting to think about a different approach (for the future) and inject this email adress in Travis. This avoids people running the application locally and spamming the "production" mail box.

Other then that, LGTM :D

**Comment by crysfel** [comment]
@emmawedekind actually I'm building from my local right now, so I need to update my `.env` file with the right value. But adding it to the example will help for sure.

@frederikprijck we need to do that, for now I'm building from my local but ideally this should be done in Travis, would you like to take that?

**Comment by frederikprijck** [comment]
@crysfel Sure, shall I create an issue so we can assign/track it ?

**Pull request merged**
