### PR TITLE
Feature/mediaqueries mobilefirst

### PR DESCRIPTION
**Pull request by tureey**
# Details

## Description

Change `mediaqueries`to respond the **mobile first** methodology and update documentation/usage. After that, update the styles to do not break anything.

## Issue

https://github.com/Coding-Coach/coding-coach/issues/107

### CODE REVIEW

**Comment by emmawedekind** [comment]
image
Should the main image disappear when the screen is resized?

**Comment by tureey** [comment]
Well @emmawedekind I did that on purpose before the mmobile designs (It's been done in the other *PR* I did). Since it should be placed *above the title* or *under the call to action* I thought I look better. But  I can change it!

**Comment by emmawedekind** [comment]
I would say place this above the title :)

**Comment by tureey** [comment]
captura de pantalla 2018-10-05 a las 13 51 10
captura de pantalla 2018-10-05 a las 13 51 25

Which one you prefer? I actually don't like any hahahah
One looks too small.
The other one looks fine but the call to action is not in the viewport, and that's not really good.

Which one do you prefer? 

PS: I am going right now to Morocco, so I'll update this on Tuesday

**Comment by emmawedekind** [comment]
Okay you can remove the image, but please remove the extras space beneath the title to compensate!

**Comment by crysfel** [comment]
Please rebase with latest in development

**Comment by tureey** [comment]
Sure. I will do it in an hour or so!

**Comment by tureey** [comment]
Since I have this error I can't commit. Any ideas? @crysfel 
captura de pantalla 2018-10-10 a las 7 47 22

**Comment by nitish24p** [comment]
@tureey 
in your `package.json`
```json
 "lint-staged": {
    "**/src/**/*.js": [
      "prettier --write",
      "eslint --fix",
      "npm run test:staged", // this change
      "git add"
    ]
  },
```

**Comment by nitish24p** [comment]
One of the PRs are fixing this anyway

**Comment by linux-nerd** [comment]
> @tureey
> in your `package.json`
> 
> ```json
>  "lint-staged": {
>     "**/src/**/*.js": [
>       "prettier --write",
>       "eslint --fix",
>       "npm run test:staged", // this change
>       "git add"
>     ]
>   },
> ```

You can use `yarn run test:staged` as well

**Comment by tureey** [comment]
So i can fix it quickly using yarn on the command, right?

I will try tomorrow. I want to end this PR ASAP or the wrong mediaqueries will be used more!

**Comment by tureey** [comment]
it worked! Thank you so much ! <3

**Comment by tureey** [comment]
Solved conflicts. Updated with `branch:development` too.

**Comment by tureey** [comment]
pump! @emmawedekind @crysfel

**Pull request merged**
