### PR TITLE
tests: run tests on Linux, macOS and Windows

### PR DESCRIPTION
**Pull request by DanielRuf**
# Details

## Description

Run tests on all platforms supported by TravisCI.

### CODE REVIEW

**Comment by DanielRuf** [comment]
I guess I'll contact the support of Travis CI because of these unstable Windows builds.

**Comment by tureey** [comment]
Yep. Would be nice to paste their response here!

**Comment by DanielRuf** [comment]
> I guess I'll contact the support of Travis CI because of these unstable Windows builds.

Wrote an email to their support. I'll update this PR when I have an answer.

**Comment by emmawedekind** [comment]
Hey @DanielRuf What's happening with this?

**Comment by DanielRuf** [comment]
Thanks for the bump. I'll trigger a new build after doing a rebase.

**Comment by crysfel** [comment]
Seems like windows environment is still failing ☹️

**Comment by DanielRuf** [comment]
I can create a new branch / env.

**Pull request closed without merging**
